@startuml

state c <<choice>>
[*] --> c : Commencer une partie
c--> Mourir: Heurter un obstacle
Mourir --> c

c --> Vivant : Esquive un obstacle / Avancer
c --> Modifie : Prends un bonus
c --> Pause : Utilisateur mets en pause

state b <<choice>>
Pause --> b

state join_state <<join>>
b --> join_state : Reprendre
b --> [*] : Quitter
Vivant--> join_state
Modifie --> join_state
join_state --> c

@enduml
