behaviors:
  GeometryDashTrainer:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 81920
      learning_rate: 0.0003
      beta: 0.0015
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50e6
    time_horizon: 50000
    summary_freq: 10000
    threaded: true